cat github env

diff --git a/.github/workflows/test_illumina_genotyping_array.yml b/.github/workflows/test_illumina_genotyping_array.yml
--- a/.github/workflows/test_illumina_genotyping_array.yml
+++ b/.github/workflows/test_illumina_genotyping_array.yml
@@ -87,29 +87,7 @@ jobs:
             echo "branch_name=${{ github.head_ref }}" >> $GITHUB_ENV
           fi
 
-      #- name: Check if method config exists
-      #  id: check-method-config
-      #  run: |
-      #    echo "Checking if method config exists..."
-      #    # Query the FireCloud API or similar service to check if the method config already exists.
-      #    METHOD_CONFIG_EXISTS=$(python3 scripts/firecloud_api/firecloud_api.py check_method_config_exists \
-      #      --workspace-namespace warp-pipelines \
-      #      --workspace-name "WARP Tests" \
-      #      --pipeline_name "$PIPELINE_NAME" \
-      #      --branch_name "$branch_name" \
-      #      --sa-json-b64 "$SA_JSON_B64" \
-      #      --user "pdt-tester@warp-pipeline-dev.iam.gserviceaccount.com")
-#
-      #    if [ "$METHOD_CONFIG_EXISTS" == "true" ]; then
-      #      echo "Method config already exists for this branch. Skipping creation."
-      #      echo "method_config_exists=true" >> $GITHUB_ENV
-      #    else
-      #      echo "Method config does not exist. It will be created."
-      #      echo "method_config_exists=false" >> $GITHUB_ENV
-      #    fi
-
       - name: Create new method configuration (only if needed)
-        #if: ${{ env.method_config_exists == 'false' }}
         run: |
           echo "Creating new method configuration for branch: $branch_name"
           METHOD_CONFIG_NAME=$(python3 scripts/firecloud_api/firecloud_api.py \
@@ -120,7 +98,7 @@ jobs:
             --branch_name "$branch_name" \
             --sa-json-b64 "$SA_JSON_B64" \
             --user "pdt-tester@warp-pipeline-dev.iam.gserviceaccount.com")
-            echo "Method Configuration Name: $METHOD_CONFIG_NAME"
+
             echo "METHOD_CONFIG_NAME=$METHOD_CONFIG_NAME" >> $GITHUB_ENV
         env:
           PIPELINE_NAME: TestIlluminaGenotypingArray
@@ -139,36 +117,35 @@ jobs:
           echo "DOCKSTORE_COMMIT_HASH=$DOCKSTORE_COMMIT_HASH_FROM_FETCH" >> $GITHUB_ENV
           echo "Dockstore Commit Hash: $DOCKSTORE_COMMIT_HASH_FROM_FETCH"
           cat $GITHUB_ENV
-
         env:
           ## TODO NEED TO ADD DOCKSTORE_TOKEN FOR SERVICE ACCOUNT ##
           DOCKSTORE_TOKEN: ${{ secrets.DOCKSTORE_TOKEN }}
           DOCKSTORE_PIPELINE_NAME: ${{ env.DOCKSTORE_PIPELINE_NAME }}
           branch_name: ${{ env.branch_name }}
 
-#      - name: Fetch Github Commit Hash
-#        id: fetch_github_commit_hash
-#        run: |
-#          echo "GITHUB_COMMIT_HASH=${{ github.sha }}" >> $GITHUB_ENV
-#          echo "GitHub Commit Hash: ${{ github.sha }}"
-#
-#      - name: Compare Dockstore and Commit Hashes
-#        id: compare_hashes
-#        run: |
-#          echo "Comparing hashes..."
-#          echo "Dockstore Commit Hash: $DOCKSTORE_COMMIT_HASH"
-#          echo "GitHub Commit Hash: $GITHUB_COMMIT_HASH"
-#
-#          if [ "$DOCKSTORE_COMMIT_HASH" != "$GITHUB_COMMIT_HASH" ]; then
-#            echo "Error: The Dockstore Commit Hash does not match the GitHub Commit Hash!"
-#            echo "Mismatch found: $DOCKSTORE_COMMIT_HASH != $GITHUB_COMMIT_HASH"
-#            exit 1
-#          else
-#            echo "Success: The Dockstore Commit Hash matches the GitHub Commit Hash."
-#          fi
-#        env:
-#          DOCKSTORE_COMMIT_HASH: ${{ env.DOCKSTORE_COMMIT_HASH }}
-#          GITHUB_COMMIT_HASH: ${{ env.GITHUB_COMMIT_HASH }}
+      - name: Fetch Github Commit Hash
+        id: fetch_github_commit_hash
+        run: |
+          echo "GITHUB_COMMIT_HASH=${{ github.sha }}" >> $GITHUB_ENV
+          echo "GitHub Commit Hash: ${{ github.sha }}"
+
+      - name: Compare Dockstore and Commit Hashes
+        id: compare_hashes
+        run: |
+          echo "Comparing hashes..."
+          echo "Dockstore Commit Hash: $DOCKSTORE_COMMIT_HASH"
+          echo "GitHub Commit Hash: $GITHUB_COMMIT_HASH"
+
+          if [ "$DOCKSTORE_COMMIT_HASH" != "$GITHUB_COMMIT_HASH" ]; then
+            echo "Error: The Dockstore Commit Hash does not match the GitHub Commit Hash!"
+            echo "Mismatch found: $DOCKSTORE_COMMIT_HASH != $GITHUB_COMMIT_HASH"
+            exit 1
+          else
+            echo "Success: The Dockstore Commit Hash matches the GitHub Commit Hash."
+          fi
+        env:
+          DOCKSTORE_COMMIT_HASH: ${{ env.DOCKSTORE_COMMIT_HASH }}
+          GITHUB_COMMIT_HASH: ${{ env.GITHUB_COMMIT_HASH }}
 
       - name: Set Test Type for PRs
         if: ${{ github.event_name == 'pull_request' }}
@@ -359,36 +336,7 @@ jobs:
           WORKSPACE: WARP Tests
           METHOD_CONFIG_NAME: ${{ env.METHOD_CONFIG_NAME }}
 
-
-      ### TODO is this even ok to do??? ###
-      - name: Decode the base64-encoded Google Cloud service account key
-        run: |
-          # Decode the base64 secret to the JSON file
-          echo ${{ secrets.PDT_TESTER_SA_B64 }} | base64 --decode > $HOME/gcloud-key.json
-          # Set GOOGLE_APPLICATION_CREDENTIALS environment variable to point to the JSON key file
-          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-key.json
-
-      - name: Authenticate with Google Cloud
-        run: |
-          gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
-
-      - name: Download the Terra Commit Hash and Compare to Github Commit Hash
-        run: |
-          gsutil cp gs://fc-cddd72b5-323c-495c-9557-5057fff0275a/commit_hash.txt .
-          export TERRA_COMMIT_HASH=$(cat commit_hash.txt)
-          echo "Terra Commit Hash: $TERRA_COMMIT_HASH"
-          echo "GitHub Commit Hash: ${{ github.sha }}"
-          
-          #compare the Terra commit hash to the github commit hash
-            if [ "$TERRA_COMMIT_HASH" != "${{ github.sha }}" ]; then
-                echo "Error: The Terra Commit Hash does not match the GitHub Commit Hash!"
-                echo "Mismatch found: Terra Commit Hash $TERRA_COMMIT_HASH != Github Commit Hash ${{ github.sha }}"
-                exit 1
-            else
-                echo "Success: The Terra Commit Hash matches the GitHub Commit Hash."
-            fi
-
-      - name: Delete Temporary Method Configuration
+      - name: Delete Method Configuration
         if: always() # Ensures it runs regardless of success or failure
         run: |
           echo "Deleting method configuration for branch: $branch_name"
@@ -405,6 +353,35 @@ jobs:
           branch_name: ${{ env.branch_name }}
           SA_JSON_B64: ${{ secrets.PDT_TESTER_SA_B64 }}
           METHOD_CONFIG_NAME: ${{ env.METHOD_CONFIG_NAME }}
+
+
+      #### TODO is this even ok to do??? ###
+      #- name: Decode the base64-encoded Google Cloud service account key
+      #  run: |
+      #    # Decode the base64 secret to the JSON file
+      #    echo ${{ secrets.PDT_TESTER_SA_B64 }} | base64 --decode > $HOME/gcloud-key.json
+      #    # Set GOOGLE_APPLICATION_CREDENTIALS environment variable to point to the JSON key file
+      #    export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-key.json
+
+      #- name: Authenticate with Google Cloud
+      #  run: |
+      #    gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
+
+      #- name: Download the Terra Commit Hash and Compare to Github Commit Hash
+      #  run: |
+      #    gsutil cp gs://fc-cddd72b5-323c-495c-9557-5057fff0275a/commit_hash.txt .
+      #    export TERRA_COMMIT_HASH=$(cat commit_hash.txt)
+      #    echo "Terra Commit Hash: $TERRA_COMMIT_HASH"
+      #    echo "GitHub Commit Hash: ${{ github.sha }}"
+      #
+      #    #compare the Terra commit hash to the github commit hash
+      #      if [ "$TERRA_COMMIT_HASH" != "${{ github.sha }}" ]; then
+      #          echo "Error: The Terra Commit Hash does not match the GitHub Commit Hash!"
+      #          echo "Mismatch found: Terra Commit Hash $TERRA_COMMIT_HASH != Github Commit Hash ${{ github.sha }}"
+      #          exit 1
+      #      else
+      #          echo "Success: The Terra Commit Hash matches the GitHub Commit Hash."
+      #      fi
 
       - name: Print Summary on Success
         if: success()
