try to auth so we can gsutilc cp

diff --git a/.github/workflows/test_illumina_genotyping_array.yml b/.github/workflows/test_illumina_genotyping_array.yml
--- a/.github/workflows/test_illumina_genotyping_array.yml
+++ b/.github/workflows/test_illumina_genotyping_array.yml
@@ -90,7 +90,8 @@ jobs:
 
       - name: Fetch Dockstore Workflow CommitID
         run: |
-          # Wait for Dockstore to update
+          # Wait 3 minutes for Dockstore to update
+          ###### TODO need to increase sleep time to 3 minutes ######
           sleep 1
           # Capture the output of the script (commit ID)
           DOCKSTORE_COMMIT_HASH_FROM_FETCH=$(python scripts/dockstore_api/fetch_dockstore_commit.py \
@@ -130,32 +131,6 @@ jobs:
   #      env:
   #        DOCKSTORE_COMMIT_HASH: ${{ env.DOCKSTORE_COMMIT_HASH }}
   #        GITHUB_COMMIT_HASH: ${{ env.GITHUB_COMMIT_HASH }}
-
-      - name: Decode the base64-encoded Google Cloud service account key
-        run: |
-          # Decode the base64 secret to the JSON file
-          echo ${{ secrets.PDT_TESTER_SA_B64 }} | base64 --decode > $HOME/gcloud-key.json
-          # Set GOOGLE_APPLICATION_CREDENTIALS environment variable to point to the JSON key file
-          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-key.json
-
-      - name: Authenticate with Google Cloud
-        run: |
-          gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
-          gsutil cp gs://fc-cddd72b5-323c-495c-9557-5057fff0275a/commit_hash.txt .
-
-      - name: Run your Google Cloud commands
-        run: |
-          # Your Google Cloud commands, e.g., gsutil or gcloud commands
-          gsutil cp gs://fc-cddd72b5-323c-495c-9557-5057fff0275a/commit_hash.txt .
-          
-
-      - name: Check gcloud auth list
-        run: |
-          python scripts/firecloud_api/gcloudauth.py --key-file="${{ secrets.PDT_TESTER_SA_B64 }}"
-        env:
-          SA_JSON_B64:
-            ${{ secrets.PDT_TESTER_SA_B64 }}
-
 
       - name: Set Test Type for PRs
         if: ${{ github.event_name == 'pull_request' }}
@@ -343,6 +318,32 @@ jobs:
           PIPELINE_NAME: TestIlluminaGenotypingArray
           NAMESPACE: warp-pipelines
           WORKSPACE: WARP Tests
+
+      - name: Decode the base64-encoded Google Cloud service account key
+        run: |
+          # Decode the base64 secret to the JSON file
+          echo ${{ secrets.PDT_TESTER_SA_B64 }} | base64 --decode > $HOME/gcloud-key.json
+          # Set GOOGLE_APPLICATION_CREDENTIALS environment variable to point to the JSON key file
+          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-key.json
+
+      - name: Authenticate with Google Cloud
+        run: |
+          gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
+
+      - name: Download the Terra Commit Hash and Compare to Github Commit Hash
+        run: |
+          gsutil cp gs://fc-cddd72b5-323c-495c-9557-5057fff0275a/commit_hash.txt .
+          export TERRA_COMMIT_HASH=$(cat commit_hash.txt)
+          echo "Terra Commit Hash: $TERRA_COMMIT_HASH"
+          
+          #compare the Terra commit hash to the github commit hash
+            if [ "$TERRA_COMMIT_HASH" != "${{ github.sha }}" ]; then
+                echo "Error: The Terra Commit Hash does not match the GitHub Commit Hash!"
+                echo "Mismatch found: Terra Commit Hash $TERRA_COMMIT_HASH != Github Commit Hash ${{ github.sha }}"
+                exit 1
+            else
+                echo "Success: The Terra Commit Hash matches the GitHub Commit Hash."
+            fi
 
       - name: Print Summary on Success
         if: success()
