cat github env

diff --git a/.github/workflows/test_illumina_genotyping_array.yml b/.github/workflows/test_illumina_genotyping_array.yml
--- a/.github/workflows/test_illumina_genotyping_array.yml
+++ b/.github/workflows/test_illumina_genotyping_array.yml
@@ -139,6 +139,7 @@ jobs:
           # Export the commit hash as an environment variable
           echo "DOCKSTORE_COMMIT_HASH=$DOCKSTORE_COMMIT_HASH_FROM_FETCH" >> $GITHUB_ENV
           echo "Dockstore Commit Hash: $DOCKSTORE_COMMIT_HASH_FROM_FETCH"
+          cat $GITHUB_ENV
 
         env:
           ## TODO NEED TO ADD DOCKSTORE_TOKEN FOR SERVICE ACCOUNT ##
@@ -152,23 +153,23 @@ jobs:
           echo "GITHUB_COMMIT_HASH=${{ github.sha }}" >> $GITHUB_ENV
           echo "GitHub Commit Hash: ${{ github.sha }}"
 
-  #    - name: Compare Dockstore and Commit Hashes
-  #      id: compare_hashes
-  #      run: |
-  #        echo "Comparing hashes..."
-  #        echo "Dockstore Commit Hash: $DOCKSTORE_COMMIT_HASH"
-  #        echo "GitHub Commit Hash: $GITHUB_COMMIT_HASH"
-#
-  #        if [ "$DOCKSTORE_COMMIT_HASH" != "$GITHUB_COMMIT_HASH" ]; then
-  #          echo "Error: The Dockstore Commit Hash does not match the GitHub Commit Hash!"
-  #          echo "Mismatch found: $DOCKSTORE_COMMIT_HASH != $GITHUB_COMMIT_HASH"
-  #          exit 1
-  #        else
-  #          echo "Success: The Dockstore Commit Hash matches the GitHub Commit Hash."
-  #        fi
-  #      env:
-  #        DOCKSTORE_COMMIT_HASH: ${{ env.DOCKSTORE_COMMIT_HASH }}
-  #        GITHUB_COMMIT_HASH: ${{ env.GITHUB_COMMIT_HASH }}
+      - name: Compare Dockstore and Commit Hashes
+        id: compare_hashes
+        run: |
+          echo "Comparing hashes..."
+          echo "Dockstore Commit Hash: $DOCKSTORE_COMMIT_HASH"
+          echo "GitHub Commit Hash: $GITHUB_COMMIT_HASH"
+
+          if [ "$DOCKSTORE_COMMIT_HASH" != "$GITHUB_COMMIT_HASH" ]; then
+            echo "Error: The Dockstore Commit Hash does not match the GitHub Commit Hash!"
+            echo "Mismatch found: $DOCKSTORE_COMMIT_HASH != $GITHUB_COMMIT_HASH"
+            exit 1
+          else
+            echo "Success: The Dockstore Commit Hash matches the GitHub Commit Hash."
+          fi
+        env:
+          DOCKSTORE_COMMIT_HASH: ${{ env.DOCKSTORE_COMMIT_HASH }}
+          GITHUB_COMMIT_HASH: ${{ env.GITHUB_COMMIT_HASH }}
 
       - name: Set Test Type for PRs
         if: ${{ github.event_name == 'pull_request' }}
