try updating usercomment

diff --git a/.github/workflows/test_illumina_genotyping_array.yml b/.github/workflows/test_illumina_genotyping_array.yml
--- a/.github/workflows/test_illumina_genotyping_array.yml
+++ b/.github/workflows/test_illumina_genotyping_array.yml
@@ -111,7 +111,7 @@ jobs:
       - name: Fetch Dockstore Workflow Commit Hash
         run: |
           # Wait 5.5 minutes for Dockstore to update
-          sleep 3
+          sleep 330
           
           DOCKSTORE_COMMIT_HASH_FROM_FETCH=$(python scripts/dockstore_api/fetch_dockstore_commit.py \
             $DOCKSTORE_TOKEN \
@@ -127,23 +127,23 @@ jobs:
           DOCKSTORE_PIPELINE_NAME: ${{ env.DOCKSTORE_PIPELINE_NAME }}
           BRANCH_NAME: ${{ env.BRANCH_NAME }}
 
-    #  - name: Compare Dockstore and Commit Hashes
-    #    id: compare_hashes
-    #    run: |
-    #      echo "Comparing hashes..."
-    #      echo "Dockstore Commit Hash: $DOCKSTORE_COMMIT_HASH"
-    #      echo "GitHub Commit Hash: $GITHUB_COMMIT_HASH"
-#
-    #      if [ "$DOCKSTORE_COMMIT_HASH" != "$GITHUB_COMMIT_HASH" ]; then
-    #        echo "Error: The Dockstore Commit Hash does not match the GitHub Commit Hash!"
-    #        echo "Mismatch found: $DOCKSTORE_COMMIT_HASH != $GITHUB_COMMIT_HASH"
-    #        exit 1
-    #      else
-    #        echo "Success: The Dockstore Commit Hash matches the GitHub Commit Hash."
-    #      fi
-    #    env:
-    #      DOCKSTORE_COMMIT_HASH: ${{ env.DOCKSTORE_COMMIT_HASH }}
-    #      GITHUB_COMMIT_HASH: ${{ env.GITHUB_COMMIT_HASH }}
+      - name: Compare Dockstore and Commit Hashes
+        id: compare_hashes
+        run: |
+          echo "Comparing hashes..."
+          echo "Dockstore Commit Hash: $DOCKSTORE_COMMIT_HASH"
+          echo "GitHub Commit Hash: $GITHUB_COMMIT_HASH"
+
+          if [ "$DOCKSTORE_COMMIT_HASH" != "$GITHUB_COMMIT_HASH" ]; then
+            echo "Error: The Dockstore Commit Hash does not match the GitHub Commit Hash!"
+            echo "Mismatch found: $DOCKSTORE_COMMIT_HASH != $GITHUB_COMMIT_HASH"
+            exit 1
+          else
+            echo "Success: The Dockstore Commit Hash matches the GitHub Commit Hash."
+          fi
+        env:
+          DOCKSTORE_COMMIT_HASH: ${{ env.DOCKSTORE_COMMIT_HASH }}
+          GITHUB_COMMIT_HASH: ${{ env.GITHUB_COMMIT_HASH }}
 
       - name: Set Test Type
         id: set_test_type
@@ -221,41 +221,12 @@ jobs:
           echo "Truth path: $TRUTH_PATH"
           RESULTS_PATH="gs://broad-gotc-test-storage/$DOCKSTORE_PIPELINE_NAME/results/$CURRENT_TIME"
           
-       #  # Create the submission_data.json file which will be the same for all inputs
-       #  SUBMISSION_DATA_FILE="submission_data.json"
-       #
-       #  # Use a heredoc to generate the JSON file content dynamically
-       #  cat <<EOF > "$SUBMISSION_DATA_FILE"
-       #  {
-       #    "methodConfigurationNamespace": "$WORKSPACE_NAMESPACE",
-       #    "methodConfigurationName": "$METHOD_CONFIG_NAME",
-       #    "useCallCache": $USE_CALL_CACHE_BOOL,
-       #    "deleteIntermediateOutputFiles": false,
-       #    "useReferenceDisks": true,
-       #    "memoryRetryMultiplier": 1.2,
-       #    "workflowFailureMode": "NoNewCalls",
-       #    "userComment": "Automated submission",
-       #    "ignoreEmptyOutputs": false
-       #  }
-       #  EOF
-          
-       #   echo "Created submission data file: $SUBMISSION_DATA_FILE"
-          
-          # 1. Submit all jobs first and store their submission IDs
-          for input_file in "$INPUTS_DIR"/*.json; do
-            test_input_file=$(python3 scripts/firecloud_api/UpdateTestInputs.py --truth_path "$TRUTH_PATH" \
-                --results_path "$RESULTS_PATH" \
-                --inputs_json "$input_file" \
-                --update_truth "$UPDATE_TRUTH_BOOL" \
-                --branch_name "$BRANCH_NAME" )
-            echo "Uploading the test input file: $test_input_file"
-
-            # Create the submission_data.json file which will be the same for all inputs
-            SUBMISSION_DATA_FILE="submission_data.json"
-              
-            # Use a heredoc to generate the JSON file content dynamically
-            cat <<EOF > "$SUBMISSION_DATA_FILE"
-            {
+          # Create the submission_data.json file which will be the same for all inputs
+          SUBMISSION_DATA_FILE="submission_data.json"
+                    
+          # Use a heredoc to generate the JSON file content dynamically
+          cat <<EOF > "$SUBMISSION_DATA_FILE"
+          {
             "methodConfigurationNamespace": "$WORKSPACE_NAMESPACE",
             "methodConfigurationName": "$METHOD_CONFIG_NAME",
             "useCallCache": $USE_CALL_CACHE_BOOL,
@@ -265,10 +236,19 @@ jobs:
             "workflowFailureMode": "NoNewCalls",
             "userComment": "Automated submission",
             "ignoreEmptyOutputs": false
-            }
-            EOF
-            echo "Created submission data file: $SUBMISSION_DATA_FILE"
-            cat $SUBMISSION_DATA_FILE
+          }
+          EOF
+          
+          echo "Created submission data file: $SUBMISSION_DATA_FILE" 
+          
+          # 1. Submit all jobs first and store their submission IDs
+          for input_file in "$INPUTS_DIR"/*.json; do
+            test_input_file=$(python3 scripts/firecloud_api/UpdateTestInputs.py --truth_path "$TRUTH_PATH" \
+                --results_path "$RESULTS_PATH" \
+                --inputs_json "$input_file" \
+                --update_truth "$UPDATE_TRUTH_BOOL" \
+                --branch_name "$BRANCH_NAME" )
+            echo "Uploading the test input file: $test_input_file"
           
             python3 scripts/firecloud_api/firecloud_api.py \
                 upload_test_inputs \
