move monitoring into submission task. ugh

diff --git a/.github/workflows/test_illumina_genotyping_array.yml b/.github/workflows/test_illumina_genotyping_array.yml
--- a/.github/workflows/test_illumina_genotyping_array.yml
+++ b/.github/workflows/test_illumina_genotyping_array.yml
@@ -215,14 +215,6 @@ jobs:
             while [ $attempt -le $MAX_RETRIES ]; do
               echo "Attempt $attempt: Submitting job for input file: $input_file"
           
-              #SUBMISSION_ID=$(python3 scripts/firecloud_api/firecloud_api2.py submit_job \
-              #          --workspace-namespace "warp-pipelines" \
-              #          --workspace-name "WARP Tests" \
-              #          --sa-json-b64 "$SA_JSON_B64" \
-              #          --user "pdt-tester@warp-pipeline-dev.iam.gserviceaccount.com" \
-              #          --submission_data_file "$SUBMISSION_DATA_FILE")
-              #
-              
               SUBMISSION_ID=$(python3 scripts/firecloud_api/firecloud_api2.py submit_job \
                --workspace-namespace "warp-pipelines" \
                --workspace-name "WARP Tests" \
@@ -247,29 +239,8 @@ jobs:
             SUBMISSION_IDS+=("$SUBMISSION_ID")
             break
           done
-          done
-          #export submission ids to github env
-          echo "submission_ids=${SUBMISSION_IDS[@]}" >> $GITHUB_ENV
-
-      - name: Monitor Workflow Status
-        run: |
-          echo "Monitoring the status of submitted workflows..."
-          # Convert the space-separated string into an array
-          IFS=' ' read -r -a submission_ids_array <<< "$submission_ids"
-          
-              # Ensure the array is populated
-          if [ ${#submission_ids_array[@]} -eq 0 ]; then
-              echo "No submission IDs found. Exiting..."
-              exit 1
-          fi
-          
-          declare -A WORKFLOW_STATUSES
-          
-          echo "submission_ids_array: ${submission_ids_array[@]}"
-          
-          for SUBMISSION_ID in "${submission_ids_array[@]}"; do
-            echo "Polling submission status for Submission ID: $SUBMISSION_ID"
-            RESPONSE=$(python3 scripts/firecloud_api/firecloud_api2.py poll_job_status \
+          echo "Polling status for submission ID: $SUBMISSION_ID"
+                      RESPONSE=$(python3 scripts/firecloud_api/firecloud_api2.py poll_job_status \
                 --submission_id "$SUBMISSION_ID" \
                 --sa-json-b64 "$SA_JSON_B64" \
                 --user "pdt-tester@warp-pipeline-dev.iam.gserviceaccount.com" \
@@ -281,33 +252,71 @@ jobs:
                 continue
             fi
           
-               # Debug raw response
-            echo "Raw Workflow Statuses:"
-            echo "$RESPONSE"
-          
-            # Parse and store workflow statuses
-            echo "Parsing workflow statuses for submissions"
             WORKFLOW_STATUSES_FOR_SUBMISSION=$(echo "$RESPONSE" | jq -r 'to_entries | map(.key + " | " + .value) | .[]')
-            echo "Raw Workflow Statuses: $WORKFLOW_STATUSES_FOR_SUBMISSION"
-            #up until here there are no issues with the script     
-    
-           # Remove duplicates and sanitize
-            CLEANED_WORKFLOW_STATUSES=$(echo "$WORKFLOW_STATUSES_FOR_SUBMISSION" | awk '!seen[$0]++')
-              # Debug cleaned statuses
-            echo "Cleaned Workflow Statuses: $CLEANED_WORKFLOW_STATUSES"
-              
-            # Reset and assign to associative array
-            WORKFLOW_STATUSES["$SUBMISSION_ID"]="$CLEANED_WORKFLOW_STATUSES"
-          
-            #Debug stored status
-             echo "Stored Workflow Statuses for $SUBMISSION_ID: ${WORKFLOW_STATUSES[$SUBMISSION_ID]}"
-
-           # Append to aggregate statuses
-            echo "Appending to aggregate statuses"
-            CLEANED_WORKFLOW_STATUSES=$(echo "$WORKFLOW_STATUSES_FOR_SUBMISSION" | tr -d '\n' | tr -d '\r')
-            echo "CLEANED_WORKFLOW_STATUSES: $CLEANED_WORKFLOW_STATUSES"
-            WORKFLOW_STATUSES["$SUBMISSION_ID"]="$CLEANED_WORKFLOW_STATUSES"
+            echo "Workflow Statuses for submission $SUBMISSION_ID: $WORKFLOW_STATUSES_FOR_SUBMISSION"
+            WORKFLOW_STATUSES["$SUBMISSION_ID"]="$WORKFLOW_STATUSES_FOR_SUBMISSION"
           done
+
+          echo "submission_ids=${SUBMISSION_IDS[@]}" >> $GITHUB_ENV
+          
+
+   #   - name: Monitor Workflow Status
+   #     run: |
+   #       echo "Monitoring the status of submitted workflows..."
+   #       # Convert the space-separated string into an array
+   #       IFS=' ' read -r -a submission_ids_array <<< "$submission_ids"
+   #
+   #           # Ensure the array is populated
+   #       if [ ${#submission_ids_array[@]} -eq 0 ]; then
+   #           echo "No submission IDs found. Exiting..."
+   #           exit 1
+   #       fi
+   #
+   #       declare -A WORKFLOW_STATUSES
+   #
+   #       echo "submission_ids_array: ${submission_ids_array[@]}"
+   #
+   #       for SUBMISSION_ID in "${submission_ids_array[@]}"; do
+   #         echo "Polling submission status for Submission ID: $SUBMISSION_ID"
+   #         RESPONSE=$(python3 scripts/firecloud_api/firecloud_api2.py poll_job_status \
+   #             --submission_id "$SUBMISSION_ID" \
+   #             --sa-json-b64 "$SA_JSON_B64" \
+   #             --user "pdt-tester@warp-pipeline-dev.iam.gserviceaccount.com" \
+   #             --workspace-namespace "warp-pipelines" \
+   #             --workspace-name "WARP Tests")
+   #
+   #         if [ -z "$RESPONSE" ]; then
+   #             echo "Failed to retrieve Workflow IDs for submission: $SUBMISSION_ID"
+   #             continue
+   #         fi
+   #
+   #            # Debug raw response
+   #         echo "Raw Workflow Statuses:"
+   #         echo "$RESPONSE"
+   #
+   #         # Parse and store workflow statuses
+   #         echo "Parsing workflow statuses for submissions"
+   #         WORKFLOW_STATUSES_FOR_SUBMISSION=$(echo "$RESPONSE" | jq -r 'to_entries | map(.key + " | " + .value) | .[]')
+   #         echo "Raw Workflow Statuses: $WORKFLOW_STATUSES_FOR_SUBMISSION"
+   #         #up until here there are no issues with the script
+   #
+   #        # Remove duplicates and sanitize
+   #         CLEANED_WORKFLOW_STATUSES=$(echo "$WORKFLOW_STATUSES_FOR_SUBMISSION" | awk '!seen[$0]++')
+   #           # Debug cleaned statuses
+   #         echo "Cleaned Workflow Statuses: $CLEANED_WORKFLOW_STATUSES"
+   #
+   #         # Reset and assign to associative array
+   #         WORKFLOW_STATUSES["$SUBMISSION_ID"]="$CLEANED_WORKFLOW_STATUSES"
+   #
+   #         #Debug stored status
+   #          echo "Stored Workflow Statuses for $SUBMISSION_ID: ${WORKFLOW_STATUSES[$SUBMISSION_ID]}"
+#
+   #        # Append to aggregate statuses
+   #         echo "Appending to aggregate statuses"
+   #         CLEANED_WORKFLOW_STATUSES=$(echo "$WORKFLOW_STATUSES_FOR_SUBMISSION" | tr -d '\n' | tr -d '\r')
+   #         echo "CLEANED_WORKFLOW_STATUSES: $CLEANED_WORKFLOW_STATUSES"
+   #         WORKFLOW_STATUSES["$SUBMISSION_ID"]="$CLEANED_WORKFLOW_STATUSES"
+   #       done
 
        #  #   # Retrieve workflow outputs
        #  #   echo "Retrieving workflow outputs for Submission ID: $SUBMISSION_ID..."
