Fixing syntax error

diff --git a/.github/workflows/validate_changelog.yml b/.github/workflows/validate_changelog.yml
--- a/.github/workflows/validate_changelog.yml
+++ b/.github/workflows/validate_changelog.yml
@@ -54,7 +54,7 @@ jobs:
       run: |
         set -e
         echo "Validating changelog for ${{ github.base_ref }}"
-        result=$(scripts/validate_release.sh -g origin/${{ github.base_ref }} 2>&1) || echo "validation_failed")  # don't exit on script failure
+        result=$(scripts/validate_release.sh -g origin/${{ github.base_ref }} 2>&1 || echo "validation_failed")  # don't exit on script failure
         # Escape newlines, carriage returns, and percent signs
         escaped_result=$(echo "$result" | sed ':a;N;$!ba;s/\r/\\r/g;s/\n/\\n/g;s/%/%%/g')
         echo "result=$escaped_result" >> $GITHUB_OUTPUT
