Adding validate versions and updating triggers.

diff --git a/.github/workflows/validate_version.yml b/.github/workflows/validate_version.yml
--- a/.github/workflows/validate_version.yml
+++ b/.github/workflows/validate_version.yml
@@ -1,29 +1,21 @@
 
-name: WARP Validate Changelog
+name: WARP Validate Version
 
 # Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the "develop" and "master" branch
-  # Uncomment this block and add your branch name to test without creating a PR
-  #push:
-    #branches: [ "kp_github_actions_pd-2113" ] 
-    #paths-ignore:
-    #  - '**/README.md'
+  # Triggers the workflow on push or pull request events but only for the "staging" and "master" branch
   pull_request:
-    #Changing trigger to all PRs for all branches
-    #branches: [ "develop" ]
-    # paths:
-    #   - 'tools/**'
+    #only for develop branch
+    #note: remove branch protection on master and staging
+    branches: [ "develop"]
+
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
-    # inputs:
-    #   image_tag:
-    #     description: 'Docker Image Tag (default: branch_name)' 
+
 env:
   PROJECT_NAME: WARP
   # Github repo name
   REPOSITORY_NAME: ${{ github.event.repository.name }}
-
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -31,12 +23,6 @@ jobs:
   validate-changelog:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
-    # defaults:
-    #   run:
-    #     working-directory: tools
-    # Map a step output to a job output
-    # outputs:
-    #   imagePath: ${{ steps.saveImagePath.outputs.url }}
     steps:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v3
@@ -50,12 +36,13 @@ jobs:
     - name: Set up Git
       run: |
         git fetch --all
-    - name: Validate changelogs
+    - name: Validate release
       id: validate_script
       run: |
         set -e
         echo "Validating changelog for ${{ github.base_ref }}"
-        result=$(scripts/validate_release.sh -g origin/${{ github.base_ref }} -i true 2>&1 || echo "validation_failed")  # don't exit on script failure
+        #scripts/validate_release.sh -g origin/staging
+        result=$(scripts/validate_release.sh -g origin/staging 2>&1 || echo "validation_failed")  # don't exit on script failure
         # Escape newlines, carriage returns, and percent signs
         escaped_result=$(echo "$result" | sed ':a;N;$!ba;s/\r/\\r/g;s/\n/\\n/g;s/%/%%/g')
         echo "result=$escaped_result" >> $GITHUB_OUTPUT
