restart

diff --git a/.github/workflows/warp_test_workflow.yml b/.github/workflows/warp_test_workflow.yml
--- a/.github/workflows/warp_test_workflow.yml
+++ b/.github/workflows/warp_test_workflow.yml
@@ -317,25 +317,26 @@ jobs:
                --workspace-name "$TESTING_WORKSPACE" \
                --sa-json-b64 "$SA_JSON_B64" \
                --user "$USER" \
-               --submission_data_file "$SUBMISSION_DATA_FILE" 2>&1)
+               --submission_data_file "$SUBMISSION_DATA_FILE")
 
+              echo "Submission ID: $SUBMISSION_ID"
           
-              # Check if submission failed
-              if [ $? -eq 0 ]; then
-                echo "Submission successful. Submission ID: $SUBMISSION_ID"
-                SUBMISSION_IDS+=("$SUBMISSION_ID")
-                break  # Exit retry loop on success
-              else
-                echo "Error submitting job: $SUBMISSION_ID"
-                echo "Retrying in $RETRY_DELAY seconds..."
-                ((attempt++))
-                if [ $attempt -gt $MAX_RETRIES ]; then
-                  echo "Max retries reached. Exiting..."
-                  exit 1
-                fi
-                sleep $RETRY_DELAY
+              if [[ "$SUBMISSION_ID" == *"404"* || -z "$SUBMISSION_ID" ]]; then
+                  echo "Error in submission, retrying in $RETRY_DELAY seconds..."
+                  ((attempt++))
+                  if [ $attempt -gt $MAX_RETRIES ]; then
+                      echo "Max retries reached. Exiting..."
+                      exit 1
+                  fi
+                  sleep $RETRY_DELAY
+                  continue
               fi
+
+              echo "Submission successful. Submission ID: $SUBMISSION_ID"
+              SUBMISSION_IDS+=("$SUBMISSION_ID")
+              break
             done
+          done
           
           echo "All jobs have been submitted. Starting to poll for statuses..."
 
